id: P004563
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01596
  title: བཅོམ་ལྡན་འདས་འཇམ་དཔལ་གཤིན་རྗེ་གཤེད་ཀྱི་འཕྲུལ་འཁོར་བྲི་ཚུལ་གྱི་མན་ངག་གསལ་བར་བཀོད་པ་གྲུབ་པའི་ཞལ་ལུང
  author: ''
  volumes: {}
